apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx-deploy-green
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx-green
  template:
    metadata:
      labels:
        run: nginx-green
    spec:
      volumes:
        - name: webdata
          emptyDir: {}
      initContainers:
        - name: web-content
          image: busybox
          volumeMounts:
            - name: webdata
              mountPath: "/webdata"
          command: ["/bin/sh", "-c", 'echo "<h1>I am <front style=\"color:green\">GREEN</front></h1>" > /webdata/index.html']
      containers:
        - image: nginx
          name: nginx
          volumeMounts:
            - name: webdata
              mountPath: "/usr/share/nginx/html"
